package ca.mcmaster.se2aa4.island.teamXXX;

public enum Biome {
    OCEAN,
    LAKE,
    BEACH,
    GRASSLAND,
    MANGROVE,
    TROPICAL_RAIN_FOREST,
    TROPICAL_SEASONAL_FOREST,
    TEMPERATE_DECIDUOUS_FOREST,
    TEMPERATE_RAIN_FOREST,
    TEMPERATE_DESERT,
    TAIGA,
    SNOW,
    TUNDRA,
    ALPINE,
    GLACIER,
    SHRUBLAND,
    SUB_TROPICAL_DESERT;
}
